### ISSUE TITLE
EC2: Block Device Attachment

### ISSUE THREAD

**Issue by Church-** [stephank/lazyssh#5]
So before I go implementing the change I figured I'd ask first.

Given the config mapping is just based on HCL I'm wondering if you support the equiv of `aws_volume_attachment` or if I'll need to add that in on my own?

**Comment by stephank** [comment]
I recently added `ebs_block_device`, but I don't think that allows attaching existing volumes, just creating new ones? https://github.com/stephank/lazyssh/blob/main/doc/providers/aws_ec2.md

So, attaching existing volumes would require some new code.

(I use HCL just as the config file format. I haven't figured out a way to bridge to Terraform; that'd be amazing but also looks like a lot of work.)

**Comment by Church-** [comment]
@stephank Yeah I was thinking of lightly borrowing the idea of the `aws_volume_attachment` resource from terraform and adding it to this project for use at work if you didn't have a plan already.

Bundle it together with say Tailscale/wireguard for a p2p vpn and SmallStep for CA based SSH Auth and it'd be perfect (which could just be included as a user/cloud-init script) for a secure, easily deployable setup.
